"job_title"
"Accounting Manager"
"Stock Manager"
"Accountant"
"Finance Manager"
"Administration Vice President"
"Programmer"
"Human Resources Representative"
"Stock Clerk"
"Marketing Representative"
"Marketing Manager"
"Purchasing Manager"
"Sales Manager"
"Administration Assistant"
"Public Relations Representative"
"President"
"Public Accountant"
"Sales Representative"
"Shipping Clerk"
"Purchasing Clerk"
