"full_name","length"
"Steven King",10
"Neena Kochhar",12
"Lex De Haan",10
"Alexander Hunold",15
"Bruce Ernst",10
"David Austin",11
"Valli Pataballa",14
"Diana Lorentz",12
"Nancy Greenberg",14
"Daniel Faviet",12
"John Chen",8
"Ismael Sciarra",13
"Jose Manuel Urman",16
"Luis Popp",8
"Den Raphaely",11
"Alexander Khoo",13
"Shelli Baida",11
"Sigal Tobias",11
"Guy Himuro",9
"Karen Colmenares",15
"Matthew Weiss",12
"Adam Fripp",9
"Payam Kaufling",13
"Shanta Vollman",13
"Irene Mikkilineni",16
"John Russell",11
"Karen Partners",13
"Jonathon Taylor",14
"Jack Livingston",14
"Kimberely Grant",14
"Charles Johnson",14
"Sarah Bell",9
"Britney Everett",14
"Jennifer Whalen",14
"Michael Hartstein",16
"Pat Fay",6
"Susan Mavris",11
"Hermann Baer",11
"Shelley Higgins",14
"William Gietz",12
